---
apiVersion: v1
kind: Service
metadata:
  name: chainlink-node-service
  namespace: default
  labels:
    app: chainlink-node-app
    environment: test
    app_name: simple_service
    app_version: v0.0.3
spec:
  selector:
    app: chainlink-node-app
  ports:
    - protocol: TCP
      port: 6688
      targetPort: chainlink-ui
