apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainlink-node
  namespace: default
  labels:
    app: chainlink-node-app
    environment: test
    app_name: simple_service
    app_version: v0.0.3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chainlink-node-app
  template:
    metadata:
      labels:
        app: chainlink-node-app
        environment: test
        app_name: simple_service
        app_version: v0.0.3
    spec:
      containers:
        - name: chainlink
          image: smartcontract/chainlink:1.3.0
          args: ["local", "n", "-p",  "/chainlink/.password", "-a", "/chainlink/.api"]
          envFrom:
          - configMapRef:
              name: chainlink-node-conf
          ports:
          - containerPort: 6688
            name: chainlink-ui
          volumeMounts:
            - name: api-volume
              mountPath: /chainlink/.api
              subPath: .api
            - name: password-volume
              mountPath: /chainlink/.password
              subPath: .password
      volumes:
        - name: api-volume
          secret:
            secretName: api-env
        - name: password-volume
          secret:
            secretName: password-env
---
apiVersion: v1
kind: Service
metadata:
  name: chainlink-node-service
  namespace: default
  labels:
    app: chainlink-node-app
    environment: test
    app_name: simple_service
    app_version: v0.0.3
spec:
  selector:
    app: chainlink-node-app
  ports:
    - protocol: TCP
      port: 6688
      targetPort: chainlink-ui
